### ISSUE TITLE
AMEEEI!

### ISSUE THREAD

**Issue by samanthaeufrasio** [mill3na/AcaPro#1]
https://github.com/mill3na/AcaPro/blob/1f547de0ae630d6892bdcf052bf4e945ba44b913/AcaPro/main.swift#L1

Eu adorei teu código. Incrível. O guia de usuário foi uma ideia ótima. Show demais <3

**Comment by mill3na** [comment]
> https://github.com/mill3na/AcaPro/blob/1f547de0ae630d6892bdcf052bf4e945ba44b913/AcaPro/main.swift#L1
> 
> Eu adorei teu código. Incrível. O guia de usuário foi uma ideia ótima. Show demais <3

Obrigada, Samantha!!
