### ISSUE TITLE
Sugestão de deslocamento de informação 

### ISSUE THREAD

**Issue by emillymaia** [mill3na/AcaPro#10]
Milena, parabéns pela criatividade e pelo seu trabalho. Eu gostei demais da forma que o readme e o programa "conversam" com o usuário, traz uma experiência de uso bem acolhedora 🥺 Tenho uma sugestão em relação a opção 1 do menu, referente ao guia do usuário (que é uma excelente ideia, pretendo me inspirar em você pra criar um também haha). Quando inserimos a opção 1, o programa retorna a seguinte informação:
<img width="441" alt="Captura de Tela 2022-04-01 às 11 42 11" src="https://user-images.githubusercontent.com/90975234/161287208-73f60a5a-3a9b-43a8-8cf4-4f1e75e25493.png">

quando isso ocorreu, eu fiquei confusa em relação ao guia, se tinha mais alguma informação ou se era apenas isso...então uma boa ideia seria apenas introduzir um print abaixo do quadro com uma mensagem do tipo: Este guia é feito em etapas, pressione enter para iniciar a leitura
apenas pra guiar o usuário mesmo 😆 no mais, está muito legal e foi muito bem feito! ❤️

**Comment by mill3na** [comment]
> Milena, parabéns pela criatividade e pelo seu trabalho. Eu gostei demais da forma que o readme e o programa "conversam" com o usuário, traz uma experiência de uso bem acolhedora 🥺 Tenho uma sugestão em relação a opção 1 do menu, referente ao guia do usuário (que é uma excelente ideia, pretendo me inspirar em você pra criar um também haha). Quando inserimos a opção 1, o programa retorna a seguinte informação: <img alt="Captura de Tela 2022-04-01 às 11 42 11" width="441" src="https://user-images.githubusercontent.com/90975234/161287208-73f60a5a-3a9b-43a8-8cf4-4f1e75e25493.png">
> 
> quando isso ocorreu, eu fiquei confusa em relação ao guia, se tinha mais alguma informação ou se era apenas isso...então uma boa ideia seria apenas introduzir um print abaixo do quadro com uma mensagem do tipo: Este guia é feito em etapas, pressione enter para iniciar a leitura apenas pra guiar o usuário mesmo 😆 no mais, está muito legal e foi muito bem feito! ❤️


Oi, Emilly! Obrigada pelo feedback!!

Verdade. Pensando por esse lado, pode não ter ficado claro mesmo. Vou dar uma modificada nas próximas alterações!
