### ISSUE TITLE
Sugestões.

### ISSUE THREAD

**Issue by Luizerz** [mill3na/AcaPro#12]
### achei algumas inconsistência durante a execução do programa foi:
<img width="861" alt="Captura de Tela 2022-04-01 às 13 31 04" src="https://user-images.githubusercontent.com/75648725/161304745-aaaf09e4-3909-43f1-8b7b-f1917d400d30.png">  
<img width="586" alt="Captura de Tela 2022-04-01 às 13 32 02" src="https://user-images.githubusercontent.com/75648725/161305071-876ee1e1-8e50-497b-9839-fbea53a3fab7.png">  
  
### Analisando o código descobri que sua função não permite que o link do site tenha números e como eu estava usando o (https://dl.acm.org/doi/fullHtml/10.1145/3015456) ele não deixava eu adicionar, a maneira mais fácil de contornar isso é não utilizar a verificação de numeral.  
```swift
let inteiros = CharacterSet.decimalDigits
let decimalRange = text.rangeOfCharacter(from: inteiros)
```
### No mais, achei seu programa extremamente importante e necessário, eu como acadêmico faço muita referencia em alguns trabalhos, mas as vezes não consigo fazer certo 😅. Logo, quando vi sua proposta fiquei super feliz xD.

**Comment by mill3na** [comment]
> ## Eae Millena 🙃,
> ### Primeiramente, parabéns pelo código, super organizado e bem legível, gostei principalmente da forma que você organizou as pastas mas, gostaria de fazer umas considerações/sugestões.
> ### O seu README.md se encontra em uma pasta que não é a "raiz" do seu projeto logo, ele não esta sendo exibido por padrão no GitHub.
> ### achei algumas inconsistência durante a execução do programa foi:
> <img alt="Captura de Tela 2022-04-01 às 13 31 04" width="861" src="https://user-images.githubusercontent.com/75648725/161304745-aaaf09e4-3909-43f1-8b7b-f1917d400d30.png">
> 
> <img alt="Captura de Tela 2022-04-01 às 13 32 02" width="586" src="https://user-images.githubusercontent.com/75648725/161305071-876ee1e1-8e50-497b-9839-fbea53a3fab7.png">
> 
> ### Analisando o código descobri que sua função não permite que o link do site tenha números e como eu estava usando o (https://dl.acm.org/doi/fullHtml/10.1145/3015456) ele não deixava eu adicionar, a maneira mais fácil de contornar isso é não utilizar a verificação de numeral.
> ```swift
> let inteiros = CharacterSet.decimalDigits
> let decimalRange = text.rangeOfCharacter(from: inteiros)
> ```
> 
> ### Pois pelo o que eu consegui entender voce não quer permitir a entrada de números na url/link mas, a meu ver é responsabilidade do usuário colocar um link valido.
> ### No mais, achei seu programa extremamente importante e necessário, eu como acadêmico faço muita referencia em alguns trabalhos, mas as vezes não consigo fazer certo 😅. Logo, quando vi sua proposta fiquei super feliz xD.

Luiz do céu!! Como eu deixei isso passaaaar??? Kkkkkkkk
Vou atualizar, novamente! Estava seguindo uma sugestão de outro issue e não me atentei a isso. Muitíssimo obrigada por me avisar!!

Obrigada pelo feedback!!
