### ISSUE TITLE
Sugestão 

### ISSUE THREAD

**Issue by btwhelena** [mill3na/AcaPro#2]
Oie Milena, tudo bem? 😊

Adorei a solução que você propôs, achei ela muito criativa, especialmente a formatação automatizada das referências, é muito útil, principalmente pra quem escreve artigos e tal 🥰

Como sugestão eu diria para especificar direitinho no **README** o que a aplicação faz e como faz, pois sem saber o que é, no inicio foi um pouco difícil de entender com o que eu estava lidando e qual seria meu objetivo como usuário

Se precisar de ajuda com qualquer coisa é só me chamar ✨

**Comment by mill3na** [comment]
> Oie Milena, tudo bem? 😊
> 
> Adorei a solução que você propôs, achei ela muito criativa, especialmente a formatação automatizada das referências, é muito útil, principalmente pra quem escreve artigos e tal 🥰
> 
> Como sugestão eu diria para especificar direitinho no **README** o que a aplicação faz e como faz, pois sem saber o que é, no inicio foi um pouco difícil de entender com o que eu estava lidando e qual seria meu objetivo como usuário
> 
> Se precisar de ajuda com qualquer coisa é só me chamar ✨

Oi!
Obrigada pelo feedback, Helena! Tentei fazer mas estava sem inspiração hehehe. Vou atualizar na bridge! <3
