### ISSUE TITLE
Um detalhe muito pequeno

### ISSUE THREAD

**Issue by JoanWilson** [mill3na/AcaPro#3]
Parabéns pelo o seu código, tive uma experiência incrível. O guia que foi criado é muito útil e seu programa foi muito bem escrito. Sobre minha Issue, percebi que no retorno, também acaba sendo imprimido esses parâmetros e uma classe. Talvez deva tenha sido esquecido ao debugar.

![Screenshot 2022-03-31 at 08 57 50](https://user-images.githubusercontent.com/48629647/161050104-8a833d4e-398b-4bf0-b426-b6597ff4b564.png)

**Comment by mill3na** [comment]
Oi, Joan!!
Obrigada pelo feedback! Implementei suas sugestões e está mais bonitinho agora hehehe.

Valeu!
