### ISSUE TITLE
Boa experiência

### ISSUE THREAD

**Issue by souzagabriela** [mill3na/AcaPro#4]
Oi Milena, antes de qualquer coisa meus parabêns pelo seu trabalho. Ficou incrível, tudo bem organizado e com muita informação, com certeza vai me ajudar muito na minha monografia, saber o que eu tenho que fazer e organizar direitinho a formatação ❤️😍

**Comment by mill3na** [comment]
> Oi Milena, antes de qualquer coisa meus parabêns pelo seu trabalho. Ficou incrível, tudo bem organizado e com muita informação, com certeza vai me ajudar muito na minha monografia, saber o que eu tenho que fazer e organizar direitinho a formatação ❤️😍

Obrigada, Gabii!!! <3
Tentarei dar continuidade para ficar ainda mais completo. As próximas atualizações (planejo eu) serão para salvar automaticamente as referências e retornar as citações também!
