### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ThaysLunes** [mill3na/AcaPro#5]
Ficou ótimo Milena. E extremamente útil, principalmente para quem escreve artigos ou outros trabalhos acadêmicos. O código está muito legível e bem estruturado.

**Comment by mill3na** [comment]
> Ficou ótimo Milena. E extremamente útil, principalmente para quem escreve artigos ou outros trabalhos acadêmicos. O código está muito legível e bem estruturado.

Obrigada, Thays!! <3
