### ISSUE TITLE
Muito bommm!!

### ISSUE THREAD

**Issue by Sunlower** [mill3na/AcaPro#6]
Eu só queria dizer que achei a ideia maravilhosa e muito útil, usarei bastante e espero que vcs continuem a ideia para a implementação de interface e afins... Lindo!

**Comment by mill3na** [comment]
> Eu só queria dizer que achei a ideia maravilhosa e muito útil, usarei bastante e espero que vcs continuem a ideia para a implementação de interface e afins... Lindo!

Muito obrigada pelo feedback!!! Darei continuidade sim hehehehe (é o plano rsrs). <3
