### ISSUE TITLE
Tenho uma sugestãozinha, mas o projeto está incrível!

### ISSUE THREAD

**Issue by Thaynara-Andrade** [mill3na/AcaPro#8]
_Oi, amei a proposta do projeto! 
Porém tenho uma sugestão, senti falta de comentários no código. Por o código ser um pouco extenso seria interessante ter comentários em linhas especificas informando o que esta sendo executado naquele bloco de instruções._

**Parabéns pela dedicação, um abraço <3!**

**Comment by mill3na** [comment]
> _Oi, amei a proposta do projeto! Porém tenho uma sugestão, senti falta de comentários no código. Por o código ser um pouco extenso seria interessante ter comentários em linhas especificas informando o que esta sendo executado naquele bloco de instruções._
> 
> **Parabéns pela dedicação, um abraço <3!**

Oi, Thaynara! Obrigada pelo feedback!! <3

Então, sobre os comentários, é o seguinte: eu sigo muito os conceitos do código limpo, que tem algumas premissas, como: 
- nomear muito bem as variáveis, funções e classes;
- fazer funções pequenas
- sempre deixar o código mais limpo e legível etc

Uma dessas premissas é justamente não comentar no código (pelo menos não excessivamente). Isso porque, quando a gente atualiza o código, é muito comum esquecermos de atualizar os comentários (e eu já fiz muito isso), principalmente se tratando de funções. 

Código limpo também diz muito sobre a legibilidade, ou seja, se o código é compreendido (esse eu tento aplicar e nem sempre consigo rs). Um código bem escrito, na verdade, dispensa comentários, acredita? Por isso meus códigos geralmente não tem comentários heheh. 

De toda forma, muito obrigada pelo retorno. Se você quiser que eu te explique melhor alguma parte do código, pode me chamar!!
